"""empty message

Revision ID: 5b2f8d6cf70e
Revises: 33894a45839c
Create Date: 2022-05-31 01:37:43.927589

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5b2f8d6cf70e'
down_revision = '33894a45839c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Artist", sa.Column('upcoming_shows_counts', existing_type=sa.INTEGER(), nullable=True, default=0))
    # ### end Alembic commands ###

def downgrade():
   op.alter_column('Artist', sa.Column('upcoming_shows_counts', existing_type=sa.INTEGER() ,nullable=True))