"""empty message

Revision ID: 88272fa575ee
Revises: d7caf052fada
Create Date: 2022-05-31 20:28:00.186878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88272fa575ee'
down_revision = 'd7caf052fada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Area', 'venues')
    op.add_column('Venue', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'Area', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'area_id')
    op.add_column('Area', sa.Column('venues', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
